sopra-fs25-group-20/sopra-fs25-group-20-client

- app/api/chat.ts
- app/hooks/useChat.ts
- app/types/chatMessage.ts
- app/utils/domain.ts
- dev/mock-server.js
- package-lock.json
- package.json
This PR adds the non-visual chat communication structure.
to back-end: type <string>, message <string>
to front-end: nickname <string>, message <string>
type can either be "join" with the room code as message or "message" with the message as message. nickname is used in the front-end to identify which message belongs to who in the history.
> Create Chat API with WebSockets

- app/components/Box.tsx
- app/components/InputField.tsx
- app/components/PrimaryButton.tsx
- app/styles/globals.css
> feat: add reusable button, input, and box components

- app/components/AppHeader.tsx
- package-lock.json
- package.json
> feat: implement AppHeader with login, GitHub link, and dark mode toggle

- app/api/apiService.ts
- app/page.tsx
- app/types/error.ts
I have used and modified `ApplicationError` and `ApiService` to abstract away the REST API calls.
> Use 'apiService' Instead of Raw Fetch

- app/components/Box.tsx
- app/components/InputField.tsx
- app/components/PrimaryButton.tsx
- app/components/chatWindow.tsx
- app/components/dropdown.tsx
- app/components/gameSettingsComponent.tsx
- app/game/[code]/page.tsx
- app/page.tsx
- app/styles/globals.css
Contains the newly added game settings component along with a refactor of the design (some css and component changes).
> Create Game Settings Component

- app/api/apiService.ts
- app/image/page.tsx
- app/styles/globals.css
> feat:Implement Ui for fetching and showing images

- app/styles/layout.css
> fix:mobile design

- app/api/gameAPI.ts
- app/components/SummaryCard.tsx
- app/components/gallery.tsx
- app/game/[code]/play.tsx
- app/styles/layout.css
- app/types/summary.ts
- add UI for spy to guess the image
- design cleanup in the summary card
> Create Image Guessing UI for Spy

- app/components/display.tsx
- app/components/hud.tsx
- app/styles/layout.css
* remove phase display
* describe your current role
* add proper timer
> Make HUD More Intuitive

- app/components/SummaryCard.tsx
- app/styles/layout.css
> fix: adjust player layout and image scaling on SummaryCard component

- app/context/ThemeContext.tsx
- app/game/[code]/lobby.tsx
- app/layout.tsx
- app/page.tsx
- app/styles/layout.css
> fix: persist dark mode across page transitions

- app/components/gallery.tsx
- app/game/[code]/play.tsx
- app/styles/style.css
- The spy can now guess an image by clicking the button that appears when selecting an image.
> Refactor Image Guessing for Spy

- app/components/Settings.tsx
- app/components/Tooltip.tsx
- app/components/chat.tsx
- app/components/dropdown.tsx
- app/components/hud.tsx
- app/styles/layout.css
- app/styles/style.css
Wrap any component inside a `<Tooltip tip="abc"></Tooltip>` to add the specified tip to the component when hovering over it.
> Implement Tooltips

- app/login/page.tsx
> feat: implement login page 

- app/components/AppHeader.tsx
> feat:conditional rendering in appheader

- app/404/page.tsx
- app/components/profileCard.tsx
- app/components/statisticsCard.tsx
- app/not-found.tsx
- app/profile/[username]/page.tsx
- app/profile/page.tsx
- app/styles/layout.css
- app/styles/style.css
- Currently, you have to manually add `username`  to the local storage for your own profile to work since it pulls the username from the local storage (which is not implemented yet).
> Add Player Profile Page With Profile and Statistics Component

- app/components/AppHeader.tsx
- app/components/createAuthPage.tsx
> feat: persist username in localStorage and validate token on app load

- app/components/Settings.tsx
- app/game/[code]/lobby.tsx
> feat:show game code in lobby and summary page

- app/components/hud.tsx
- app/components/statisticsCard.tsx
- app/components/voting.tsx
- app/styles/layout.css
* add button to return to game setup page to statistics card
* fix layout bug in lobby and during voting
* fix timer not refreshing
> Add Button to Profile Which Redirects to Game Setup

- app/components/Button.tsx
- app/components/PlayerOverview.tsx
- app/components/Settings.tsx
- app/components/chat.tsx
- app/game/[code]/lobby.tsx
- app/game/[code]/page.tsx
- app/game/[code]/play.tsx
- app/gamesetup/page.tsx
- app/styles/style.css
* additionally, add a button cooldown
> Prevent Game From Being Played With Less than Three Players
